author_string: Microsoft
copyright_string: Copyright 2022
description_string: Project Mu IPMI Feature Package.
license_url: https://opensource.org/licenses/BSD-2-Clause
name: fernald-feature-ipmi
project_url: https://github.com/microsoft/mu_feature_ipmi
server_url: https://api.nuget.org/v3/index.json
tags_string: ''
