## @file
# Release Package Action.
#
# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Build Release Package

on:
  release:
    types:
      - published

env:
  PACKAGE: IpmiFeaturePkg/
  PACKAGE_DIR: _package/
  NUSPEC_FILE: _package.nuspec
  RELEASE_LOG: _package/release_log.txt

jobs:
  build:
    name: Build Release Package
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Prepare Release Files
        run: |
          mkdir -p ${{ env.PACKAGE_DIR }}
          cp -R ${{ env.PACKAGE }} ${{ env.PACKAGE_DIR }}
      - name: Create Release Log
        run: |
          echo --------------------------------------------            > ${{ env.RELEASE_LOG}}
          echo "Copyright (C) Microsoft Corporation"                  >> ${{ env.RELEASE_LOG}}
          echo "SPDX-License-Identifier: BSD-2-Clause-Patent"         >> ${{ env.RELEASE_LOG}}
          echo --------------------------------------------           >> ${{ env.RELEASE_LOG}}
          echo "Release:   ${{ github.event.release.name }}"          >> ${{ env.RELEASE_LOG}}
          echo "Tag:       ${{ github.event.release.tag_name }}"      >> ${{ env.RELEASE_LOG}}
          echo "Published: ${{ github.event.release.published_at }}"  >> ${{ env.RELEASE_LOG}}
          echo "URL:       ${{ github.event.release.html_url }}"      >> ${{ env.RELEASE_LOG}}
          echo --------------------------------------------           >> ${{ env.RELEASE_LOG}}
          echo "${{ github.event.release.body }}"                     >> ${{ env.RELEASE_LOG}}
      - name: Create Nuspec File
        run: |
          echo '<package>'                                                                                          > ${{ env.NUSPEC_FILE }}
          echo '  <metadata>'                                                                                      >> ${{ env.NUSPEC_FILE }}
          echo '      <id>mu-feature-ipmi</id>'                                                                    >> ${{ env.NUSPEC_FILE }}
          echo '      <version>${{ github.event.release.tag_name }}</version>'                                     >> ${{ env.NUSPEC_FILE }}
          echo '      <description>Project Mu IPMI Feature Package.</description>'                                 >> ${{ env.NUSPEC_FILE }}
          echo '      <authors>Microsoft</authors>'                                                                >> ${{ env.NUSPEC_FILE }}
          echo '      <licenseUrl>https://opensource.org/licenses/BSD-2-Clause</licenseUrl>'                       >> ${{ env.NUSPEC_FILE }}
          echo '      <projectUrl>https://github.com/${{ github.repository }}.git</projectUrl>'                    >> ${{ env.NUSPEC_FILE }}
          echo '      <copyright>Copyright (c) Microsoft Corporation</copyright>'                                  >> ${{ env.NUSPEC_FILE }}
          echo '      <tags />'                                                                                    >> ${{ env.NUSPEC_FILE }}
          echo '      <repository type="git" url="https://github.com/${{ github.repository }}.git"></repository>'  >> ${{ env.NUSPEC_FILE }}
          echo '  </metadata>'                                                                                     >> ${{ env.NUSPEC_FILE }}
          echo '  <files>'                                                                                         >> ${{ env.NUSPEC_FILE }}
          echo '      <file src="${{ env.PACKAGE_DIR }}**" target="/" />'                                          >> ${{ env.NUSPEC_FILE }}
          echo '  </files>'                                                                                        >> ${{ env.NUSPEC_FILE }}
          echo '</package>'                                                                                        >> ${{ env.NUSPEC_FILE }}
          cat ${{ env.NUSPEC_FILE }}
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
      - name: Pack Nuget Package
        run: nuget pack
      - name: Push Nuget Package
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
